### ISSUE TITLE
feature request: Support JSON config

### ISSUE THREAD

**Issue by aereal** [mackerelio/mackerel-container-agent#11]
# Request

- mackerel-container-agent supports JSON as valid and parseable configuration format

# Motivation

Currently available serialization format of the config is only YAML.

YAML is very complicated and difficult to implement the spec properly.
So it is difficult to find *proper* YAML serialize/deserialize library.

In contrast, JSON and its serialize/deserialize implementations are more stable and simple than YAML (in my opinion).

If we can use JSON as config format, it will be easier to generate the config programatically, such as using AWS CDK).

**Comment by itchyny** [comment]
Thanks for your request. Currently mackerel-container-agent does accepts JSON as the configuration format since YAML is a superset of JSON and thus yaml library parses JSON as well. You can write JSON in your MACKEREL_AGENT_CONFIG.

**Comment by aereal** [comment]
> yaml library parses JSON as well

Wow, it's crazy but very useful... Thank you!
