### ISSUE TITLE
パッケージ取得元 のエラー

### ISSUE THREAD

**Issue by kobarasukimaro** [mackerelio/mackerel-container-agent#57]
下記 URL (http://apt.mackerel.io/v2/) が現在 `AccessDenied` となっていて、 `apt-update` に失敗するためいくつかのパッケージがインストールできない状態となっております。
一旦下記URLをリポジトリから除外することによりこの状況を回避しておりますが、リポジトリの正常化が正しい対応かと考えてますのでご対応をお願いできればと存じます。

https://github.com/mackerelio/mackerel-container-agent/blob/45502da49a18ed34c8cb685c5c09382d85cb302b/Dockerfile.plugins#L13

**Comment by tanatana** [comment]
パッケージ取得でエラーが出る件について報告ありがとうございます。
検証いたしましたが、こちらの環境では再現が確認できない状況です。

お手数ですが、以下のページの「サポートチームへ連絡」ボタンからお問い合わせいただけますでしょうか? その際ですが
- ご利用中のオーガニゼーション名
- 実際に表示されたエラーメッセージ
- container agent をお使いの環境

などを含めていただけますとスムーズです。
https://mackerel.io/ja/docs/#contact-human

**Comment by kobarasukimaro** [comment]
ありがとうございます。承知しました。
そちらで問い合わせますのでこの Issue はクローズします。
